import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => localStorage.setItem('pi-locale', 'en'));
  const card = { id: 'layout-fixture', cwd: process.cwd(), session: null, phase: 'draft', createdAt: Date.now() };
  const queue = { version: 1, revision: 1, cards: [card], order: [card.id], workspaces: [] };
  await page.route('**/api/card-queue', route => {
    const body = route.request().postDataJSON();
    if (body?.action === 'claim') card.detached = { owner: body.owner, expiresAt: Date.now() + 120000 };
    return route.fulfill({ json: queue });
  });
  await page.goto(`http://127.0.0.1:30141/?card=${card.id}`);
  const left = page.getByRole('button', { name: 'Toggle left sidebar', exact: true });
  const right = page.getByRole('button', { name: 'Toggle right sidebar', exact: true });
  await left.waitFor();
  assert.equal(await left.evaluate(el => el.parentElement.firstElementChild === el), true);
  assert.equal(await right.evaluate(el => el.parentElement.lastElementChild === el), true);
  const leftPanel = page.locator('#detached-explorer');
  const rightPanel = page.locator('#detached-tools');
  const settle = () => page.waitForTimeout(300);
  const width = async el => (await el.boundingBox())?.width ?? 0;
  const drag = async (selector, dx) => {
    const rect = await page.locator(selector).boundingBox();
    await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
    await page.mouse.down();
    await page.mouse.move(rect.x + rect.width / 2 + dx, rect.y + rect.height / 2, { steps: 8 });
    await page.mouse.up();
    await settle();
  };
  await settle();
  // Theme view transitions temporarily suppress hit testing on the old surface.
  await page.waitForFunction(() => { const el = document.querySelector('.sidebar-resize-handle'); const r = el?.getBoundingClientRect(); return r && el.contains(document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2)); });
  const initialLeft = await width(leftPanel);
  await drag('.sidebar-resize-handle', 60);
  assert.equal(await width(leftPanel), initialLeft + 60);
  await right.click(); await settle();
  const initialRight = await width(rightPanel);
  await drag('.right-panel-resize-handle', 50);
  assert.equal(await width(rightPanel), initialRight - 50);
  assert.ok(await width(page.locator('article')) >= 420);
  await page.locator('.sidebar-resize-handle').focus();
  await page.keyboard.press('ArrowLeft'); await settle();
  const saved = await width(leftPanel);
  await left.click(); await settle(); assert.equal(await width(leftPanel), 0);
  await left.click(); await settle(); assert.equal(await width(leftPanel), saved);
  await page.reload(); await left.waitFor(); await settle(); assert.equal(await width(leftPanel), saved);
  await page.setViewportSize({ width: 800, height: 900 });
  await right.click(); await settle();
  assert.equal(await page.locator('.right-panel-resize-handle').isVisible(), false);
  await page.locator('.cq-task-panel-heading button').last().click();
  await page.setViewportSize({ width: 390, height: 844 }); await settle();
  assert.equal(await left.getAttribute('aria-expanded'), 'false');
  await left.click(); await settle();
  await page.locator('.cq-drawer-backdrop').click({ position: { x: 380, y: 400 } });
  assert.equal(await left.getAttribute('aria-expanded'), 'false');
  await right.click(); await settle();
  assert.equal(await width(rightPanel), 390);
  await page.locator('.cq-task-panel-heading button').last().click(); await settle();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.setViewportSize({ width: 1440, height: 900 }); await left.click(); await right.click(); await settle();
  await page.locator('.cq-task-explorer').getByText('package.json', { exact: true }).click();
  await page.locator('.cq-task-viewer').waitFor();
  await page.waitForTimeout(600);
  await page.screenshot({ path: '/tmp/detached-layout.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: titlebar edges, both pointer resizers, keyboard resize, persistence, minimum chat width, compact overlay, mobile drawers, no overflow or browser errors');
} finally { await browser.close(); }
